### ISSUE TITLE
HYUNDAI AVANTE XD 2002 DELUX 1.5 DOHC MODEL 사양 최신화 및 WORKING POSITION 취득

### ISSUE THREAD

**Issue by JY-AUTOMOTIVE** [pyj9293/AOB#14]
기존에 작성한 입력사양을 최신화하고 출력사양도 추가할 예정입니다.
또한 입력사양이 확정되었기에 WORKING POSITION 취득하여 추가하겠습니다.

상기의 건은 구글 드라이브에 업로드 하겠습니다.

**Comment by JY-AUTOMOTIVE** [comment]
@pyj9293 @sangwooAhn 

사양서 최신화 하였으며 WORKING POSITION 전체 취득 완료했습니다.
구글 드라이브에 업로드 했으니 확인 바랍니다.

우리는 약 30개의 입력을 받게 됩니다.
커넥터는 32핀 정도로 선정하면 되겠네요.

계기판 커넥터별 핀 사양도 정리해서 시트2에 올렸습니다.
어려운 용어는 해설까지 적어놓았으므로 최소한 우리가 따는 사양에 대해
왜 따는지, 이게 무슨 기능을 하는지 정도는 각자 공부 바랍니다.

어려운 부분은 물어보시면 친절히 답변 드리겠습니다.

이상입니다.
이제 이슈 리뷰로 옮기겠습니다.

감사합니다.

**Comment by sangwooAhn** [comment]
@JY-AUTOMOTIVE 구글 드라이브에 업로드 되어있는 문서들 확인 했습니다.
친절한 설명까지 GOOD 수고하셨습니다.
