### ISSUE TITLE
차량에서 브레이크 전개 정도 조사

### ISSUE THREAD

**Issue by pyj9293** [pyj9293/AOB#2]
해야 할일
1. 액셀, 브레이크 전개 정도 ( 얼마나 밟았는지 ) 입력 가능한지 조사
2. 상세하게 이슈에 올릴 것

**Comment by sangwooAhn** [comment]
1. 엑셀과 브레이크의 전개정도 측정

** case 1 ( 가솔린 차량에서의 엑셀 전개정도  )**

가솔린 차량의 경우 엑셀레이터는 흡입공기의 양을 조절하는 "스로틀 밸브"와 연관되어 있습니다.
엑셀레이터를 밟게 되면 엑셀포지션 센서가 밟은 정도를 인지해 ECU로 데이터 값을 보내고, 스로틀 밸브가 이 값을 토대로 열리게 됩니다.

스로틀 바디에 장착되어 있는 센서가 스로틀 밸브의 개도된 정도와 시간을 측정하여 ECU로 데이터를 보내고 인젝터라는 연료분사장치가 ECU에 있는 정보를 바탕으로 흡입된 공기의 양에 해당하는 연료를 분사하게 됩니다.

기화기 또는 스로틀 보디를 통과하는 공기량을 조절하기 위해 여닫는 밸브를 말하는데, 액셀러레이터 페달은 이 밸브가 열리는 정도를 조절한다.
공기가 많이 통과하면 이에 따라 휘발유도 많이 흡입되며, 엔진이 공기를 빨아들이지 않을 때는 아무리 액셀러레이터 페달을 밟아도 가속되지 않는 것은 이 때문이다.

![default](https://user-images.githubusercontent.com/29588177/38474971-0e4c497a-3b94-11e8-8445-486e9cbcd948.JPG)

출처 : http://terms.naver.com/entry.nhn?docId=1655664&cid=42330&categoryId=42330



**case 2 ( 디젤 차량에서의 엑셀 전개정도 )** 

디젤 차량의 경우 스로틀밸브가 없거나 개도되어 있는 상태입니다. 열려있는 상태이기 때문에 흡입되는 공기의 양은 무한하고, 가속페달을 밟게 되면 엑셀포지션 센서가 ECU로 데이터 값을 보내고 연료분사를 하는 인젝터가 이 값을 인지해 적정 연료를 분사하여 공기와 섞여 압축, 착화가 일어나 동력이 발생합니다.

결론적으로 가솔린, 디젤차량의 엑셀의 밟은 정도는 ECU에서 받아올 수 있습니다.


**case 3 ( 브레이크의 전개 정도 )**

브레이크 패달을 발으면 패달에 연결된 관에 차있는 브레이크액 ( 브레이크 오일 )이 밀려나면서 이 액체가 브레이크 패드를 밀어내 패드가 디스크로터와 접촉하게 되면서 제동이 됩니다.
이를 디스크 브레이크 시스템이라고 합니다.

![default](https://user-images.githubusercontent.com/29588177/38476012-1c2b972e-3b9b-11e8-8af1-72e72d6d4ec7.JPG)

위 사진의 파란색 부분이 캘리퍼라는 부품이고, 캘리퍼 안의 브레이크 패드가 브레이크 로터를 잡아주면서 제동이 걸립니다.

드럼 브레이크도 존재하는데 원리는 디스크 브레이크와 비슷하나 원통이 있고 그 원통안에 작은 원이 있어 브레이크를 밟으면 작은 원이 그 원통에 접촉하며 제동이 됩니다.
드럼브레이크는 패드 대신 패드 열할을 하는 라이닝이 있습니다.

![default](https://user-images.githubusercontent.com/29588177/38476125-aa4bc8a8-3b9b-11e8-8d5c-1d7a44778ecd.JPG)

오너가 브레이크 페달을 밟게 되면 유압이 드럼브레이크의 휠실린더 까지 전달됩니다. 휠실린더는 브레이크슈를 작동시키게 되고, 슈에 부착되어 있는 라이닝이 드럼을 잡아줍니다.

ECU에서 정도를 측정하는 부분이 없이 물리적인 압력으로 제어를 하는 방식입니다.

결론적으로
엑셀의 밟은 정도는 측정이 가능하나,
브레이크의 밟은 정도는 측정이 불가능합니다.

**Comment by JY-AUTOMOTIVE** [comment]
@sangwooAhn 아반떼xd도 브레이크는 기계적(유압)에 의해서만 작동하고 따로 전개정도 등을 ecu로 전달하지는 않는다는거군요? 알겠습니다. 엑셀 관련해서는 회의 때 논의할 것이 있습니다. 브레이크 포함.

**Comment by sangwooAhn** [comment]
@JY-AUTOMOTIVE 네 알겠습니다.
추가적으로 웹서치중에 DAG-3라는 제품을 찾았는데.
현재 저희가 개발하려는 제품과 상당히 유사한...? 것 같습니다.
ECU에서 제공해주는 값들에 대해서 얻을 정보가 많은것 같아 공유 드립니다.
ps. 위 정보들도 아래 사이트에서 알게된 내용 입니다.

http://cafe.naver.com/dag2012

**Comment by pyj9293** [comment]
@sangwooAhn 이슈 확인했습니다. 고생하셨습니다.
