### ISSUE TITLE
현대 아반떼(2002) XD의 사양 조사

### ISSUE THREAD

**Issue by pyj9293** [pyj9293/AOB#3]
해야 할일
1. Pin Map
2. I/O
3. PWL
4. Select Sensor
5. Select GPS Module
6. 조사한 사이트도 링크 걸어주세요.

**Comment by JY-AUTOMOTIVE** [comment]
오늘 열이 37도에 목이 맛탱이가 가고 콧물 재채기가 심하여.... 오늘 아침부터 회사 가려고했는데 어지러워서 침대에만 누워있습니다... 하루만 더 미뤄주시면... 회사에 대부분 조사한 자료는 다 있는데 정리하기가....

**Comment by JY-AUTOMOTIVE** [comment]
안녕하십니까?
HYUNDAI AVANTE XD 2002 DELUX MODEL 1.5 DOHC
차량의 환경 분석해서 엑셀로 정리 후 우리의 구글 드라이브에 업로드 했습니다.

해당 자료는 공개적으로 구할 수 없는 자료이기에 해당 코멘트에 등록하지 않고
드라이브에 올려놓았으니 접속하셔서 다운로드 후 확인하시기 바랍니다.
*기밀은 항상 유지바랍니다.

향후 문제가 될만한 이슈사항 언급합니다.
1. ECU DATA USING
  - 일전에 각 계통 장치로부터 ECU로 인풋되는 SIGNAL을 사용하자는 이슈가 있었습니다.
당사 프로젝트 진행에 있어 ECU로 INPUT되는 SIGNAL을 사용하는 것이 더욱 정확한
주행 DATA를 취득할 수 있는 것은 사실입니다. 하지만 금일 자료 분석 결과
이는 바람직하지 않다는 결론을 도출했습니다. 하기에 사유 기재하겠습니다.

사유) 우리가 ECU와 AOB 회로를 연동하여 사용하게되면 AOB에 대해 엄격한 H/W,
S/W, 기구 품질관리가 보증되어야 합니다. 추가로 10만 시간 이상의 신뢰성 TEST 및
고온 및 상온TEST(-40~85˚C), 진동 TEST, LONG TIME TEST, EMC TEST 등 현재 완성차 시장에서
요구하는 엄격한 품질 TEST를 모두 통과해야 ECU 연동이 가능합니다.
모두 아시겠지만 ECU는 자동차 엔진과 관련된 전자적 컨트롤을 담당하는 유닛입니다.
따라서 완성차 시장에서도 ECU 이슈는 S++로 관리하고 0.000001%의 오류도 용납하지 않습니다.
ECU와 연동되는 장비(자율 주행, ADAS 등)또한 MOBIS에서 A+로 관리하는 업체에서만
개발을 허용하고 해당 업체도 MOBIS에 장기 출장나가서야 개발이 가능합니다.
만약 당사에서 개발한 회로에서 역기전류, 익스플로어 전압, S/W 오작동, H/W 간섭이
발생할 경우 ECU에 오신호를 전달할 수 있고 이는 실차 주행시 중대한 사고로 이어집니다.
(급발진, 커넥팅로드 파손, 엔진 노킹, 누유, 엔진 파손, 브레이크 오작동, 시동꺼짐, 출력저하)
본인 혹은 주변차량으로부터 큰 인명피해를 유발할 수 있으므로 우리가 ECU를 연동하는 것은
시기상조라고 생각합니다. 차후 기술력이 증대된 후에 접근할 수 있으리라 판단합니다.

2. 차후 진행방향에 대해서 안건 제시합니다.

A) AOB 사양 확정
B) WORKING POSITION 취득(SIGNAL LINE 취득할 위치 선정)
C) 실차 분해 후 SIGNAL LINE 취득
D) SIGNAL 분석장비 제조
E) JY AUTOMOTIVE 워크샵 진행
E-1) 워크샵 장소 이동중에 실차 SIGNAL TEST
E-2) SIGNAL 기록
F) 해당 DATA를 기반으로 개발 착수


상기와 같이 자료 조사 및 향후 개발방향 확립 완료합니다.

차후 회의에서 해당 내용 중점적으로 논의해야합니다.
추가로 개인이 생각하고 있는 이슈 종합해서 안건상정 바랍니다.


이상입니다.
감사합니다.

**Comment by JY-AUTOMOTIVE** [comment]
@kdh1234 고대혁 팀장님.
우리 사양 픽스되면 즉각 커넥터 라인(SIGNAL LINE)취득 준비해야합니다.
준비 부탁드립니다.
