### ISSUE TITLE
사고 기록 장치에서의 I/O 조사

### ISSUE THREAD

**Issue by pyj9293** [pyj9293/AOB#6]
@kdh1234 EDR(Event Data Recoder)에 대한 기본적인 I/O 조사 부탁드립니다.

**작성 방법**

_Input_
- 이름 :
- 센서 모델명 :
- 설명 :

_Output_
- 이름 :
- 센서 모델명 :
- 설명 :

**문서화(Excel, Word) 시켜도 상관 없습니다.**

**Comment by JY-AUTOMOTIVE** [comment]
@pyj9293 해당 이슈는 삭제 부탁드립니다. 현 진행사항과 거리감이 있어 삭제 후 당사 진행방향에 맞게 수정해서 올리겠습니다.
