### ISSUE TITLE
AOB_GUI Program 화면 설계서 작성

### ISSUE THREAD

**Issue by pyj9293** [pyj9293/AOB#9]
@JY-AUTOMOTIVE AOB GUI Program 화면설계 부탁드립니다.

**방법**

1. 
![inked _li](https://user-images.githubusercontent.com/16908979/38600499-4d569f32-3d9f-11e8-8b66-b76260734c3f.jpg)

2.
![default](https://user-images.githubusercontent.com/16908979/38600505-53c35cde-3d9f-11e8-932b-9afc0e212517.PNG)

3.
![111](https://user-images.githubusercontent.com/16908979/38600718-144f8914-3da0-11e8-912d-20c1e1cea34f.png)

4.
![1](https://user-images.githubusercontent.com/16908979/38600507-58042c7e-3d9f-11e8-99de-f0090ad53377.PNG)

5.
![2](https://user-images.githubusercontent.com/16908979/38600511-5b2d970a-3d9f-11e8-8bae-5ff40d86e713.PNG)

**More Shape에서 찾아 보시면 다른 모양도 많으니 참고하여 작성 바랍니다.**

_경로 : 구글 드라이브/JY AUTOMOTIVE/1. AOB PROJECT/2. S/W/3.설계/4.화면 설계서_

이상입니다.

**Comment by JY-AUTOMOTIVE** [comment]
@pyj9293 아반떼XD 사양서 세번째 SHEET 보시면 계기판 그림이 있습니다. 되도록 이대로 가려고 합니다. 익일부터 작업 진행하겠습니다. 궁금한점은 카톡이나 위챗으로 여쭤보겠습니다. 이상입니다. 감사합니다.

**Comment by JY-AUTOMOTIVE** [comment]
@pyj9293 @sangwooAhn 

구글드라이브->JY AUTOMOTIVE->AOB PROJECT->1.H/W 폴더 진입하시면
JY AUTOMOTIVE DRIVE PLAYER_180423 이란 파일이 있습니다.
또한 GUI 설명화면_180422 이란 엑셀파일이 있습니다.

두개의 자료 참고하셔서 GUI 구성 프로그래밍 부탁합니다.
이대로 이슈 마감하겠습니다.

**Comment by JY-AUTOMOTIVE** [comment]
@pyj9293 

아 어디에 저장하라고 경로 지정 해주셨네요.
구글 드라이브/JY AUTOMOTIVE/1. AOB PROJECT/2. S/W/3.설계/4.화면 설계서
여기에 파일 저장하겠습니다.

**Comment by sangwooAhn** [comment]
@JY-AUTOMOTIVE 확인 했습니다.
